Add reload method
amberframework/granite pull request #491
Opened 2023-10-16 15:14 UTC by stufro

Resolves #485

2023-10-16 18:51 UTC, crimson-knight commented
This is basically an alias of `find!`, and the test example shows that it's meant to be used when you modify the record outside of the object. Other than the convenience of using `.reload` instead of `Model.find!()`, what's the benefit of adding this method?

Do you have a use case?

2023-10-16 21:13 UTC, stufro commented
We have 2 use cases for it. 

The first is reloading a record in specs:

```crystal
person = Person.create
PersonUpdater.run
person.reload.field.should eq "new value"
```

The second is in a distributed system when running more than 1 instance of the same service, you might want to reload the record in case another instance has updated the db record since it was loaded into memory. 

So yeah I agree it is just a convenience method, happy to go with your judgment 😊

2023-10-17 11:38 UTC, a-alhusaini commented
Might I suggest renaming it to `sync` instead of reload?

Or maybe `resync`.. since you're syncronizing with the database.. `reload` is an ok term but it is more imperative than declarative.. 

I think resync/sync are better names but I think we can come up with something better if we thought about it.

2023-10-17 12:19 UTC, crimson-knight commented
I think this would be helpful in the test suite, so let's wrap this in a macro that checks for the `Spec` module before it's included.

Can you also add the documentation to the code comments? Now that we have the crystaldoc.info I want to ensure we're writing docs that the community at large can consume in as many places as possible.

2023-10-17 15:06 UTC, stufro commented
Sure thing all done. 1 questions about the docs, when running `crystal docs` the reload method doesn't appear I'm assuming because the condition in the macro isn't met. Do you know a good way to deal with this?

2023-10-20 14:36 UTC, crimson-knight requested changes

2023-10-20 14:36 UTC, crimson-knight commented on src/granite/querying.cr
> +    def reload
```suggestion
    def reload
      {% if !@top_level.has_constant? "Spec" %}
        raise "#reload is a convenience method for testing only, please use #find in your application code"    
      {% end %}
```

2023-10-20 14:36 UTC, crimson-knight commented on src/granite/querying.cr
> +  {% if parse_type("Spec").resolve? %}
Just remove this macro that wraps everything in favor of the macro inside of the method itself

2023-10-26 18:45 UTC, crimson-knight approved these changes

2023-10-26 18:45 UTC, merged